GET http://34.54.16.210/reservations/
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODdmNzlhNGQ0NWJiNjgxZGU4MTA0OGIiLCJpYXQiOjE3NTMyNjgzNDUsImV4cCI6MTc1MzI3MTk0NX0.U6ICVHcre2APtQ-Q7bvFmLA8M29YOlr7gGoDk_5osHw;