# @no-cookie-jar #

POST http://34.54.16.210/reservations/
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODdmNzlhNGQ0NWJiNjgxZGU4MTA0OGIiLCJpYXQiOjE3NTMyNjgzNDUsImV4cCI6MTc1MzI3MTk0NX0.U6ICVHcre2APtQ-Q7bvFmLA8M29YOlr7gGoDk_5osHw;
Content-Type: application/json

{
  "startDate": "2025-10-01T00:00:00.000Z",
  "endDate": "2025-10-02T00:00:00.000Z",
  "placeId": "1234567890abcdef12345678",
  "invoiceId": "0987654321fedcba09876543",
  "charge": {
    "amount": 17,
    "card": {
      "cvc": "333",
      "exp_month": 10,
      "exp_year": 2026,
      "number": "4242 4242 4242 4242"
    }
  }
}