GET http://localhost:3000/reservations/
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODgzNmJjN2VmYjhiN2U4NGE3YjAwNDAiLCJpYXQiOjE3NTM0NDMyOTAsImV4cCI6MTc1MzQ0Njg5MH0.0y4OKNhd-MD-yA0oW1OuP90h3vnqMl8PdOr-p50Au-E