# @no-cookie-jar #

POST http://127.0.0.1:43333/reservations
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODdmNzlhNGQ0NWJiNjgxZGU4MTA0OGIiLCJpYXQiOjE3NTMxODQ3MDQsImV4cCI6MTc1MzE4ODMwNH0.aGiXWh6C7swqyOTL-MftBxHHK8siVM-nqgWZWMS_VMo;
Content-Type: application/json

{
  "startDate": "2025-10-01T00:00:00.000Z",
  "endDate": "2025-10-02T00:00:00.000Z",
  "placeId": "1234567890abcdef12345678",
  "invoiceId": "0987654321fedcba09876543",
  "charge": {
    "amount": 5,
    "card": {
      "cvc": "333",
      "exp_month": 10,
      "exp_year": 2026,
      "number": "4242 4242 4242 4242"
    }
  }
}