apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - image: asia-southeast1-docker.pkg.dev/sleepr-466416/reservations/production
          name: reservations
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: PORT
              value: '3004'
            - name: AUTH_HOST
              value: 'auth-tcp'
            - name: AUTH_PORT
              value: '3002'
            - name: PAYMENTS_HOST
              value: 'payments'
            - name: PAYMENTS_PORT
              value: '3001'
          resources:
            requests:
              memory: '1Gi'
              cpu: '250m'
            limits:
              memory: '2Gi'
              cpu: '500m'
          ports:
            - containerPort: 3004
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - asia-southeast1-a
                      - asia-southeast1-b
                      - asia-southeast1-c
                      - asia-southeast2-a
                      - asia-southeast2-b
                      - asia-southeast2-c
